In [1]:
import numpy as np

# Data

In [3]:
R1 = np.array([[1, 0.3, 0.8, 0.5, 1],
               [0.6, 1, 0.7, 0.3, 0.7],
               [0.6, 0, 1, 0.9, 0.1],
               [0.3, 1, 0.6, 1, 0.4],
               [0.2, 0, 0.1, 0.1, 1]])
R2 = np.array([[1, 0, 1, 0, 0.6],
               [1, 1, 0.9, 0.4, 1],
               [0, 0.7, 1, 0, 0.7],
               [0.5, 0.3, 0, 1, 0.7],
               [1, 0.9, 0.8, 0.3, 1]])
lambda1 = 0.3
lambda2 = 0.7

# Step - 1

$$Q_1=\lambda_1 R_1\cap\lambda_2 R_2$$

In [5]:
Q1 = np.minimum(lambda1 * R1, lambda2 * R2)
Q1

array([[0.3 , 0.  , 0.24, 0.  , 0.3 ],
       [0.18, 0.3 , 0.21, 0.09, 0.21],
       [0.  , 0.  , 0.3 , 0.  , 0.03],
       [0.09, 0.21, 0.  , 0.3 , 0.12],
       [0.06, 0.  , 0.03, 0.03, 0.3 ]])

# Step - 2

$$Q_2=\lambda_1 R_1 + \lambda_2 R_2$$

In [6]:
Q2 = lambda1 * R1 + lambda2 * R2

# Step - 3 - strong preference relation


In [7]:
def calculate_difference_matrix(Q):
    n = Q.shape[0]
    Q_revers = np.zeros((n, n), dtype=float)
    Q_diff = np.zeros((n, n), dtype=float)
    
    # Reverse the matrix
    for i in range(n):
        for j in range(n):
            Q_revers[i][j] = Q[j][i]
    
    # Compute the difference
    for i in range(n):
        for j in range(n):
            Q_diff[i][j] = Q[i][j] - Q_revers[i][j]
            if Q_diff[i][j] < 0:
                Q_diff[i][j] = 0
                
    return Q_diff

Q1_diff = calculate_difference_matrix(Q1)
Q2_diff = calculate_difference_matrix(Q2)

In [8]:
Q1_diff

array([[0.  , 0.  , 0.24, 0.  , 0.24],
       [0.18, 0.  , 0.21, 0.  , 0.21],
       [0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.09, 0.12, 0.  , 0.  , 0.09],
       [0.  , 0.  , 0.  , 0.  , 0.  ]])

In [9]:
Q2_diff

array([[0.  , 0.  , 0.76, 0.  , 0.  ],
       [0.79, 0.  , 0.35, 0.  , 0.28],
       [0.  , 0.  , 0.  , 0.09, 0.  ],
       [0.29, 0.14, 0.  , 0.  , 0.37],
       [0.04, 0.  , 0.07, 0.  , 0.  ]])

# Step - 4 
$$\mu_Q(x)=1-sup_{y\in X} \mu^2_Q(x, y)$$

In [21]:
def calculate_alternatives(Q_diff):
    n = Q_diff.shape[0]
    alternatives = np.zeros(n, dtype=float)
    
    for i in range(n):
        alternatives[i] = round(1 - max(Q_diff[:, i]), 3)
    
    return alternatives

def calculate_alternatives_in_both(alternatives1, alternatives2):
    return np.minimum(alternatives1, alternatives2)


In [22]:
alternatives_Q1 = calculate_alternatives(Q1_diff)
alternatives_Q2 = calculate_alternatives(Q2_diff)

In [23]:
alternatives_Q1

array([0.82, 0.88, 0.76, 1.  , 0.76])

In [24]:
alternatives_Q2

array([0.21, 0.86, 0.24, 0.91, 0.63])

In [25]:
alternatives_in_Q1_and_Q2 = calculate_alternatives_in_both(alternatives_Q1, alternatives_Q2)

print('Alternatives in Q1 and Q2:\n', alternatives_in_Q1_and_Q2)

Alternatives in Q1 and Q2:
 [0.21 0.86 0.24 0.91 0.63]
