In [1]:
import pandas as pd
import numpy as np
from scipy.optimize import linprog

In [4]:
productivity = np.array([
    [10, 40, 10],
    [50, 10, 50],
    [60, 40, 30]
    ])

cost = np.array([
    [20, 14, 25],
    [30, 25, 15],
    [15, 20, 20]
    ])
constraint = np.array([400, 300, 480])

In [5]:
total_work = f"f(x)="

for i in range(3):
    for j in range(3):
        total_work += f"{productivity[i][j]}x_{i+1}{j+1}+"

total_cost = f"f(x)="

for i in range(3):
    for j in range(3):
        total_cost += f"{cost[i][j]}x_{i+1}{j+1}+"

total_work = total_work[:-1]
total_cost = total_cost[:-1]
print(total_work+" -> max")
print(total_cost+" -> min")
for i in range(3):
    print(f"x_{i+1}1+x_{i+1}2+x_{i+1}3 <= {constraint[i]}")
print("x_11,...,x_33 => 0")

f(x)=10x_11+40x_12+10x_13+50x_21+10x_22+50x_23+60x_31+40x_32+30x_33 -> max
f(x)=20x_11+14x_12+25x_13+30x_21+25x_22+15x_23+15x_31+20x_32+20x_33 -> min
x_11+x_12+x_13 <= 400
x_21+x_22+x_23 <= 300
x_31+x_32+x_33 <= 480
x_11,...,x_33 => 0


In [43]:
c = [-10, -40, -10, -50, -10, -50, -60, -40, -30]
A = [[1, 1, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 1, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 1, 1]]

b = [400, 300, 480]
x_bounds = (0, None) 

res = linprog(c, A_ub=A, b_ub=b, bounds=[x_bounds] * 9, method='highs')

print("Optimal work:")
optimal_hours = res.x.reshape(3, 3)
print(optimal_hours)
print("Optimal cost:")
actuals = -res.fun
print(actuals)  


Optimal work:
[[  0. 400.   0.]
 [300.   0.   0.]
 [480.   0.   0.]]
Optimal cost:
59800.0


In [44]:
c = [-10, -40, -10, -50, -10, -50, -60, -40, -30]
A = [[1, 1, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 1, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 1, 1],
     [20, 14, 25, 30, 25, 15, 15, 20, 20]]  


b = [400, 300, 480, 12000]  
x_bounds = (0, None)

res = linprog(c, A_ub=A, b_ub=b, bounds=[x_bounds] * 9, method='highs')

print("Optimal work:")
optimal_hours = res.x.reshape(3, 3)
print(optimal_hours)
print("Optimal work:")
print(-res.fun)  
print("Cost of work")
print((A[3]*res.x).sum())

Optimal work:
[[  0.          21.42857143   0.        ]
 [  0.           0.         300.        ]
 [480.           0.           0.        ]]
Optimal work:
44657.142857142855
Cost of work
12000.0
